networks:
  kafka-net:
    driver: bridge

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    networks:
      - kafka-net

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    depends_on:
      - redpanda
    environment:
      REDPANDA_BROKERS: "redpanda:9092"
    ports:
      - "8080:8080"
    networks:
      - kafka-net
